In [69]:
import numpy as np

### 벡터 연산

- 요소들에 대한 연산을 벡터 연산으로 처리하면 일반적인 for반복문으로  연산 작업을 처리하는 것 보다 월등히 뛰어난 처리 속도로 효율적인 작업 가능

In [70]:
# 0부터 시작하여 10000000개 요소를 가진 배열 생성
x = np.arange(100000000)
x

array([       0,        1,        2, ..., 99999997, 99999998, 99999999])

In [71]:
%%time
# 해당 셀을 수행하는데 소요된 시간을 표기해주는 주피터노트북 명령어
# 셀의 가장 상단에 위치해야함(주석 포함해서 가장 상단에 위치해야함.)

# 반복문을 통한 합계(x변수에 저장한 넘파이 배열 자료 총합 구하기)
# 시간단위 : 1s = 1,000ms(밀리세컨드) = 1,000,000㎛(마이크로세컨드)
loop_result = 0
for i in x:
    loop_result += i
print(loop_result)

<timed exec>:8: RuntimeWarning: overflow encountered in long_scalars


KeyboardInterrupt: 

In [94]:
%%time
# 벡터연산(넘파이명령어)를 통한 합계 연산
np.sum(x)

CPU times: total: 0 ns
Wall time: 0 ns


10

In [95]:
%%time
x.sum()

CPU times: total: 0 ns
Wall time: 0 ns


10

In [96]:
# (공통) 라이브러리 불러오기 및 사용자 함수 정의
import numpy as np

def np_print(nparr):
    print('''
    type : {}  
    shape : {}  
    dimension : {}  
    dtype : {}
    data :\n {}
    '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

### 배열 정렬

- sort(axis = -1) 메서드 : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 원본 객체에 정렬 결과가 반영됨
    
- np.sort(axis = -1) : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 정렬된 새로운 배열을 반환함
    
- np.argsort(arr) : 정렬 순서를 반환
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬

In [97]:
# 1차원 배열 생성
x = np.arange(0, 5)
np_print(x)


    type : <class 'numpy.ndarray'>  
    shape : (5,)  
    dimension : 1  
    dtype : int32
    data :
 [0 1 2 3 4]
    


In [98]:
# 기본 파이썬 문법으로 순번 뒤집기
x[::-1]

array([4, 3, 2, 1, 0])

In [99]:
# 난수 패턴 고정
np.random.seed(20)

In [100]:
# 오름차순 정렬
a = np.random.randint(0, 10, 5)
np_print(a)


    type : <class 'numpy.ndarray'>  
    shape : (5,)  
    dimension : 1  
    dtype : int32
    data :
 [3 9 4 6 7]
    


In [101]:
# 1. np.sort(자료) -> 원본에 반영되진 않음
np.sort(a)

array([3, 4, 6, 7, 9])

In [102]:
a

array([3, 9, 4, 6, 7])

In [103]:
# 2. arr.sort() -> 원본 자료 변경
a.sort()
a

array([3, 4, 6, 7, 9])

In [104]:
a

array([3, 4, 6, 7, 9])

In [105]:
b = np.random.randint(0, 10, 5)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (5,)  
    dimension : 1  
    dtype : int32
    data :
 [2 0 6 8 5]
    


In [106]:
# np.argsort(자료)는 내부의 아이템들을 오름차순 정렬하기 위해서
# 현재 몇 번 인덱스에 있는 자료를 어디에 배치해야 하는지 보여줌
np.argsort(b)

array([1, 0, 4, 2, 3], dtype=int64)

In [107]:
# 0이상 1미만의 범위에서 무작위로 실수값을 가지는 3행 3열의 배열 2개 생성
a = np.random.random((3, 3))
b = np.random.random((3, 3))
np_print(a)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.65795147 0.19385022 0.2723164 ]
 [0.71860593 0.78300361 0.85032764]
 [0.77524489 0.03666431 0.11669374]]
    

    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.7512807  0.23921822 0.25480601]
 [0.85762553 0.94977903 0.56168686]
 [0.17878052 0.77025193 0.49238104]]
    


##### 예) 2차원 배열의 경우

기본값 axis = -1 <br>
현재 배열의 axis = 0, 1 <br>
마지막 axis = 1 (row별 정렬)

<img src='img/sortaxis1.jpg' width='200' height='200' align='left'>

In [108]:
# 기본 방향(axis = -1) -> 행별 정렬
np_print(a)
np.sort(a)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.65795147 0.19385022 0.2723164 ]
 [0.71860593 0.78300361 0.85032764]
 [0.77524489 0.03666431 0.11669374]]
    


array([[0.19385022, 0.2723164 , 0.65795147],
       [0.71860593, 0.78300361, 0.85032764],
       [0.03666431, 0.11669374, 0.77524489]])

##### axis = 0 (열별 정렬)

<img src='img/sortaxis0.jpg' width='200' height='200' align='left'>`

In [109]:
# 열별 정렬
np_print(a)
np.sort(a, axis=0)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.65795147 0.19385022 0.2723164 ]
 [0.71860593 0.78300361 0.85032764]
 [0.77524489 0.03666431 0.11669374]]
    


array([[0.65795147, 0.03666431, 0.11669374],
       [0.71860593, 0.19385022, 0.2723164 ],
       [0.77524489, 0.78300361, 0.85032764]])

## 인덱싱(Indexing), 슬라이싱(Slicing)

### 1. 인덱싱 : 하나의 요소에 대해 참조
- 각 차원에 따라 배열이 참조하는 인덱스의 개수가 다름
    - 1차원 배열 : 인덱스 1개
    - 2차원 배열 : 인덱스 2개
    - 3차원 배열 : 인덱스 3개

- 인덱싱으로 참조한 요소에 대해 수정 가능

- 인덱스 배열을 전달하여 여러 개의 요소 참조

In [110]:
# 0부터 23까지 1씩 증가하는 값을 아이템으로 가지는 1차원 배열 생성
arr1 = np.arange(0, 24)
np_print(arr1)


    type : <class 'numpy.ndarray'>  
    shape : (24,)  
    dimension : 1  
    dtype : int32
    data :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    


In [111]:
# 1차원 배열 인덱싱 : 1번 인덱스 요소 접근
arr1[1]

1

In [112]:
# 1차원 배열 인덱싱 : 마지막 요소 접근
arr1[-1]

23

In [113]:
# 1차원 배열 인덱싱을 통한 값 수정
arr1[-1] = 100
arr1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22, 100])

In [114]:
# 배열 arr1을 이용해 4 x 6 형태의 2차원 배열 arr2 만들기
arr2 = arr1.reshape(4, 6)
np_print(arr2)


    type : <class 'numpy.ndarray'>  
    shape : (4, 6)  
    dimension : 2  
    dtype : int32
    data :
 [[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22 100]]
    


In [115]:
# 2차원 배열 인덱싱 : 2차원배열[행인덱스, (열인덱스)]
# 하나의 행에 접근 : 1행
arr2[0]

array([0, 1, 2, 3, 4, 5])

In [116]:
arr2[1][3]

9

In [117]:
# 하나의 열에 접근 : 모든 행에 대해서 하나의 열에 접근
# 반환값 : 1d array
arr2[:, 1]

array([ 1,  7, 13, 19])

In [118]:
# 하나의 값에 접근
arr2[2][2]

14

In [119]:
arr2[2, 2]

14

In [120]:
# 여러개의 행 조회
arr2[[0, 3]]

array([[  0,   1,   2,   3,   4,   5],
       [ 18,  19,  20,  21,  22, 100]])

In [121]:
# 여러개의 열 조회
arr2[:, [0, 2]]

array([[ 0,  2],
       [ 6,  8],
       [12, 14],
       [18, 20]])

In [122]:
# 0번째, 2번째 로우의 3번째, 5번째 컬럼을 가져오도록 처리해보세요
arr2[[0, 2]][:, [3, 5]]

array([[ 3,  5],
       [15, 17]])

In [123]:
arr2[[0, 2]]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17]])

In [124]:
# 2차원 배열 인덱싱을 통한 값 수정
# 하나의 행/열에 대해 모두 동일한 값으로 수정 : 전달하는 값을 스칼라값으로 전달
# 서로 다른 값으로 수정 : 배열 구조에 맞춰서 자료 전달
# 하나의 값을 수정하는 예시
arr2[2] = 9
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])

In [125]:
# 단일 값이 아닌 여러 값을 대입하고 싶을때는
arr2[1] = [9, 9, 9, 99, 99, 99]
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  9,   9,   9,  99,  99,  99],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])

In [126]:
np_print(arr2)


    type : <class 'numpy.ndarray'>  
    shape : (4, 6)  
    dimension : 2  
    dtype : int32
    data :
 [[  0   1   2   3   4   5]
 [  9   9   9  99  99  99]
 [  9   9   9   9   9   9]
 [ 18  19  20  21  22 100]]
    


In [127]:
# 3차원 배열 생성
# 구조 : 2개의 층(페이지, 면), 4행 3열
# np.arange() => 24개의 size
arr3 = np.arange(0, 24).reshape((2, 4, 3))
np_print(arr3)


    type : <class 'numpy.ndarray'>  
    shape : (2, 4, 3)  
    dimension : 3  
    dtype : int32
    data :
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
    


In [128]:
# 3차원 배열 인덱싱 : arr[면, 행, 열]
# 0번째 면(페이지)에 접근
arr3[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [129]:
# 첫 번째(0) 면, 1번 행에 접근
arr3[0, 1]

array([3, 4, 5])

In [130]:
# 첫 번째 면, 1번 행, 0번 열에 접근
arr3[0, 1, 0]

3

In [131]:
# 3차원 배열 역시 배열 인덱싱으로 값 수정이 가능하다
# 스칼라 연산을 통한 동일한 값으로 수정
# arr3의 2번 면(1번 인덱스)를 0으로 일괄 변경해주세요.
arr3[1] = 0
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [132]:
# 하나의 면에 대해 서로 다른 값으로 수정 : 1번면, 1번행을 [1, 2, 3]으로 바꿔주세요.
arr3[1, 1] = [1, 2, 3]
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  0,  0],
        [ 1,  2,  3],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [133]:
# 아니면 아예 3 * 4형식으로 대입을 해버리는 방법도 있습니다.
arr3[0] = [[10, 20, 30],
          [40, 50, 60],
          [0, 0, 0],
          [0, 0, 0]]

In [134]:
arr3

array([[[10, 20, 30],
        [40, 50, 60],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 1,  2,  3],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [135]:
# 인덱스 배열을 전달하여 여러 개의 요소 참조
# (기존 인덱싱 방법) 0번째 장 0행 0열, 1행 1열, 2행 2열 요소에 접근
#arr3[0, 0, 0] # 10
#arr3[0, 1, 1] # 50
arr3[0, 2, 2] # 0

0

In [136]:
# 여러 개의 인덱싱을 배열로 전달
# (행0, 열0), (행1, 열1), (행2, 열2)
# 3차원 배열일 경우에 : [페이지, [[0, 1, 2], [0, 1, 2]]]
# arr3[면, 행, 열]-> 만약 여러 단위를 조회할때는 이중리스트로 입력
# 삼중리스트 입력시 이중리스트 요소를 반복
arr3[0, [[0, 1, 2], [0, 2, 3]]]
#arr3[0:, [0, 1, 2]]

array([[[10, 20, 30],
        [40, 50, 60],
        [ 0,  0,  0]],

       [[10, 20, 30],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

### 2. 슬라이싱 : 여러 개의 요소에 대해 참조
- axis 별로 범위 지정
    - from_index : 시작 인덱스(포함), 0일 경우 생략 가능
    - to_index : 종료 인덱스(미포함), 마지막 인덱스일 경우 생략 가능
    - step : 연속되지 않은 범위의 경우 간격 지정
- 열만 조회하는 경우 : 전체 행에 슬라이싱으로 접근 후 특정 열을 조회

In [137]:
# 0부터 23까지 1씩 증가하는 정수값을 가지는 1차원 배열 생성
a = np.arange(0, 24)
np_print(a)


    type : <class 'numpy.ndarray'>  
    shape : (24,)  
    dimension : 1  
    dtype : int32
    data :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    


In [138]:
# 1차원 배열 슬라이싱 : 1번부터 4번까지 접근
a[1:5]

array([1, 2, 3, 4])

In [139]:
# 1번째 인덱스로부터 14번째 인덱스까지 2개씩 건너뛰며 접근
a[1:15:2]

array([ 1,  3,  5,  7,  9, 11, 13])

In [140]:
# 2차원 배열 생성
b = a.reshape(6, 4)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (6, 4)  
    dimension : 2  
    dtype : int32
    data :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
    


In [141]:
# 2차원 배열 슬라이싱 : 0행부터 3행까지 접근
# 2d_array[행(:열:간격)]
b[0:4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [142]:
# 1행부터 4행에 대해서, 2열부터 3열까지 접근
b[1:5, 2:4]

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [143]:
# 2차원 배열 슬라이싱을 통한 값 수정
# 1행부터 4행에 대해 2열부터 3열까지의 모든 배열에 대해서 수정
s_arr = b[1:5, 2:4]
s_arr

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [144]:
# 0번째 행과 마지막 열을 제외한 모든 값을 99로 수정
s_arr[1:, :-1] = 99
s_arr

array([[ 6,  7],
       [99, 11],
       [99, 15],
       [99, 19]])

In [145]:
# 얕은복사로 인한 원본배열의 변경
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 99, 11],
       [12, 13, 99, 15],
       [16, 17, 99, 19],
       [20, 21, 22, 23]])

In [146]:
# 2차원 배열 슬라이싱 : 연속되지 않은 범위의 열에 대한 인덱싱
# step1. 전체 행에 대해서 접근
# step2. 여러 개의 열 인덱싱 배열 전달
# b의 전체 행 + 1, 3번째 열
# b[행, 열]
b[:, [1, 3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23]])

### 연습문제

아래 정보는 학생들의 학번, 영어 성적, 국어 성적, 수학 성적 정보 입니다. <br>
해당 정보를 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 국어 성적, 네번째 행에 수학 성적을 저장한 배열로 만들고 학생별로 영어 성적을 오름차순 기준으로 각 열(column)을 정렬하세요.

<img src='img/sort_q1.png' align='left'>

In [147]:
data = [[1, 2, 3, 4],
       [70, 97, 45, 56],
       [87, 84, 33, 67],
       [46, 80, 75, 78]]
arr = np.array(data)

In [148]:
np_print(arr)


    type : <class 'numpy.ndarray'>  
    shape : (4, 4)  
    dimension : 2  
    dtype : int32
    data :
 [[ 1  2  3  4]
 [70 97 45 56]
 [87 84 33 67]
 [46 80 75 78]]
    


In [149]:
# 영어 성적을 기준으로 오름차순 정렬
np.sort(arr)

array([[ 1,  2,  3,  4],
       [45, 56, 70, 97],
       [33, 67, 84, 87],
       [46, 75, 78, 80]])

In [150]:
# 힌트 : argsort()
# 영어에 해당하는 부분에 argsort()를 걸면 해당 자료들을 어디 배치해야할지 나옵니다.
# 그 인덱스 번호를 전체 행에 적용하시면 됩니다.
i = np.argsort(arr[1])
i

array([2, 3, 0, 1], dtype=int64)

In [151]:
arr[:, i]

array([[ 3,  4,  1,  2],
       [45, 56, 70, 97],
       [33, 67, 87, 84],
       [75, 78, 46, 80]])

### 조건 색인(Boolean Indexing)

- 배열의 요소에 대해 조건을 적용하여 True, False로 조건에 대한 결과 반환
- True에 해당하는 요소만 조회하여 조건을 만족하는 결과 반환

In [152]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 99, 11],
       [12, 13, 99, 15],
       [16, 17, 99, 19],
       [20, 21, 22, 23]])

In [153]:
# 스칼라 연산을 이용해 10보다 큰 요소 조회하기
b > 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [154]:
# 조건색인 방법
# 자료[자료를 포함한 조건식]
b[b>10]

array([99, 11, 12, 13, 99, 15, 16, 17, 99, 19, 20, 21, 22, 23])

In [155]:
b[b>10].size

14

In [156]:
# 조건색인을 이용해 b에서 짝수인 자료만 남겨보세요
# 조건색인에 2개 이상의 조건을 걸고 싶을때는 각 조건 하나하나마다 ()로 감싸주고
# 조건사이를 and인 경우 &로, or인 경우는 |로 연결해준다.
b[(b%2==0) & (b!=0)]

array([ 2,  4,  6,  8, 12, 16, 20, 22])

### 연습문제

조건색인을 활용해 공무원시험의 합격자 평균을 구해주세요.
합격점수는 60점 이상입니다.

아래는 시험 점수 결과입니다.<br>
[31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34,
       55, 56, 51]

In [157]:
data =[31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34,55, 56, 51]

In [158]:
score = np.array(data)
score

array([31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34,
       55, 56, 51])

In [159]:
score[score>=60].mean()


77.33333333333333

### 배열 복사

- 인덱싱, 슬라이싱을 통해 반환된 배열은 원본 배열에 대해 독립적인 새로운 객체가 아닌 원본 배열과 종속적인 객체
- 원본과 독립적인 복사본인 배열을 생성 : arr.copy() / np.copy(arr)

In [160]:
a = [1, 2, 3]
a2 = [1, 2, 3]

In [161]:
# 얇은복사
b = a

In [162]:
# 깊은복사 1
c = a2[:]

In [163]:
b[0]

1

In [164]:
c[0]

1

In [165]:
print(a,a2)

[1, 2, 3] [1, 2, 3]


In [166]:
b[0] = 10
c[0] = 10

In [167]:
print(a, a2)

[10, 2, 3] [1, 2, 3]


### 배열 변환

#### 1. 전치(Transpose)

- 배열의 행/열 인덱스가 바뀌는 변환
- 배열객체.T : 행/열 인덱스가 바뀐 새로운 배열을 반환하며 원본은 변경되지 않음

<img src='img/transpose.png' width='200' height='200' align='left'>

In [168]:
# 1이상 12이하의 값을 가지는 3 * 4 구조의 배열 생성
arr1 = np.arange(1, 13).reshape(3,4)
np_print(arr1)


    type : <class 'numpy.ndarray'>  
    shape : (3, 4)  
    dimension : 2  
    dtype : int32
    data :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
    


In [169]:
# 구조를 바꿔서 보여줌
arr1.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [170]:
# 원본에는 영향이없음
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 2. 배열 형태 변경

- arr.ravel(), np.ravel(arr)
    - 다차원 배열을 1차원 배열로 변환
    - np.ravel() : 1차원으로 변환되는 결과는 원본 배열에 반영되지 않음
    - arr.ravel() : 1차원으로 변환하는 배열의 요소가 변경되면 원본 배열에도 반영됨
    
    
- arr.reshape(new_shape), np.reshape(arr, new_shape)
    - 원본 배열 객체의 구조(shape)를 변경
    - 변경하려는 구조의 전체 요소 개수와 원본 배열의 전체 요소 개수가 동일해야 함
    - 변경하려는 구조의 튜플 중 하나의 원소는 -1로 대체할 수 있고 다른 하나의 원소를 기준으로 계산되어 사용됨
    - reshape() 메서드가 반환하는 배열의 요소가 변경되면 원본 배열에도 반영됨

In [171]:
# 다차원 배열을 1차원 배열로 변환
arr2 = arr1.ravel()

In [172]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [173]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [174]:
# 변환 후 값 수정, 원본과 비교
arr2[0] = 10

In [175]:
arr1

array([[10,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [176]:
arr2

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [177]:
# arr1을 6 * 2로 바꾸되 하나의 축에 대해 -1을 사용해봅시다
arr3 = arr1.reshape(-1,2)
arr3

array([[10,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [178]:
# 변환 후 값 수정, 원본과 비교
arr3[0] = [100,200]

In [179]:
arr1

array([[100, 200,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

#### 3. 요소 변경, 추가, 삭제


1) 요소 변경
- arr.resize(new_shape), np.resize(arr, new_shape)
    - 배열 메서드를 사용하면 원본 변경, np 함수를 사용하면 새로운 배열 반환
    - 배열의 구조(shape)를 변경하며 원본 배열의 요소 수와 동일하지 않아도 변경 가능
    - 변경되는 배열의 요소 수가 동일할 경우 : reshape() 메서드와 동일한 결과
    - 변경되는 배열의 요소 수가 더 많을 경우
        - np.resize(arr, new_shape) : 원본을 변경하지 않고, 모자란 부분을 기존 배열 값에서 복사해서 추가
        - arr.resize(new_shape) : 원본을 변경하고, 모자란 부분을 0으로 채움
        - 공통적으로 new_shape은 튜플로 추가
    - 변경되는 배열의 요소 수가 더 작을 경우 : 마지막 남은 요소 삭제

In [180]:
# 변경되는 배열의 요소 수가 동일한 경우 : reshape()와 동일하게 동작함
arr.resize(5,3)

In [181]:
arr.size

15

In [184]:
np_print(arr)


    type : <class 'numpy.ndarray'>  
    shape : (5, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[ 1  2  3]
 [ 4 70 97]
 [45 56 87]
 [84 33 67]
 [46 80 75]]
    


In [188]:
# 변경 후 배열의 요소 갯수가 더 많은 경우
arr3 = np.resize(arr2, (6,3))
np_print(arr3)


    type : <class 'numpy.ndarray'>  
    shape : (6, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[100 200   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]
 [100 200   3]
 [  4   5   6]]
    


In [190]:
# refcheck = False인 경우만 크기가 다를 때 0으로 남는 자리를 채워줌
arr.resize((6,3), refcheck=False)
np_print(arr)


    type : <class 'numpy.ndarray'>  
    shape : (6, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[ 1  2  3]
 [ 4 70 97]
 [45 56 87]
 [84 33 67]
 [46 80 75]
 [ 0  0  0]]
    


In [191]:
# 변경되는 배열의 요소 수가 더 적은 경우 : 마지막 남은 요소를 삭제
# 크기가 원본과 resize를 이용했을 때 다르다면 refcheck = False를 반드시 넣는다.
arr.resize((3,3), refcheck=False)
np_print(arr)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[ 1  2  3]
 [ 4 70 97]
 [45 56 87]]
    


2) 요소 추가
- np.append(arr, values, axis=None)
    - arr 마지막에 values를 추가
    - axis 지정하지 않는 경우(기본값) : 1차원 배열로 변형되어 결합
    - axis = 0 : 행 방향으로 결합 (단, 열의 개수가 동일해야 함)
    - axis = 1 : 열 방향으로 결합 (단, 행의 개수가 동일해야 함)
    - 원본 배열들에 반영되지 않음

In [193]:
# 1이상 10미만의 볌위에서 1씩 증가하는 숫자로 3 * 3 구조의 배열 a 생성
# 10이상 19미만의 범위에서 1씩 증가하는 숫자로 3 * 3 구조의 배열 b 생성

a = np.arange(1, 10).reshape(3,3)
b = np.arange(10, 19).reshape(3,3)
np_print(a)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
    

    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
    


In [194]:
# 2개의 배열 결합
# axis를 지정하지 않는 경우 : np.append(arr1, arr2) => axis = None
# arr1, arr2 모두 1차원으로 변형해서 추가함
np.append(a,b)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [196]:
## 2개의 배열 결합
# axis=0 : 행 단위 결합 : 열 개수는 3개로 동일
np.append(a,b, axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [197]:
# 2개의 배열 결합
# axis=1 : 열 방향으로 결합 / 행 개수는 동일
np.append(a,b, axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [200]:
# 열의 개수가 다른 배열과의 결함
c = np.arange(30,45).reshape(3,5)
np_print(c)


    type : <class 'numpy.ndarray'>  
    shape : (3, 5)  
    dimension : 2  
    dtype : int32
    data :
 [[30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]
    


In [204]:
# a와 c를 결합해주세요
np.append(a,c, axis=1)

array([[ 1,  2,  3, 30, 31, 32, 33, 34],
       [ 4,  5,  6, 35, 36, 37, 38, 39],
       [ 7,  8,  9, 40, 41, 42, 43, 44]])

In [203]:
# 방향을 바꾸면 에러나는것도 확인해주세요.
np.append(a,c, axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5

In [205]:
# 행 단위로 결합할 수 있는 구조로 변경(resize 활용)
c.resize((5,3))
c

array([[30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [206]:
np.append(a,c, axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [207]:
# 행 개수가 다른 배열과의 결합
d = np.arange(90, 102).reshape(4,3)
np_print(d)


    type : <class 'numpy.ndarray'>  
    shape : (4, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[ 90  91  92]
 [ 93  94  95]
 [ 96  97  98]
 [ 99 100 101]]
    


In [208]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [209]:
np.append(b,d, axis=0)

array([[ 10,  11,  12],
       [ 13,  14,  15],
       [ 16,  17,  18],
       [ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 100, 101]])

In [212]:
np.append(b,d.reshape(3,4), axis=1)

array([[ 10,  11,  12,  90,  91,  92,  93],
       [ 13,  14,  15,  94,  95,  96,  97],
       [ 16,  17,  18,  98,  99, 100, 101]])

- np.insert(arr, idx, values, axis=None)
    - 지정한 인덱스(idx)에 value를 추가
    - axis 지정하지 않는 경우(기본값) : 1차원 배열의 변형되고 해당 인덱스에 추가
    - axis = 0 : 행 방향으로 n번째 행에 추가
    - axis = 1 : 열 방향으로 n번째 열에 추가
    - 원본 배열에 반영되지 않음
   

In [214]:
# 1이상 10미만 범위에서 1씩 증가하는 숫자로 3 x 3 구조의 배열 생성
arr = np.arange(1,10).reshape(3,3)
np_print(arr)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
    


In [215]:
# axis 지정하지 않는 경우 : arr를 1차원 배열로 변형한 후
# 변형된 배열의 지정 index에 값 추가
# 2d array를 1d array로 변형, 1번 인덱스에 100추가
np.insert(arr,1, 100)

array([  1, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [216]:
# 원본 배열은 유지
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [218]:
# axis =0 : 행 방향으로 index번째 행을 추가
# a배열의 1번 인덱스 행에 100을 추가 =>> 행의 요소 개수(열 개수)만큼 100이 추가됨
np.insert(arr, 1, 100, axis=0)

array([[  1,   2,   3],
       [100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [219]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [221]:
# axis =1 열 방향으로 index 번째 행을 추가
# a 배열의 2번 인덱스 열에 200 추가
np.insert(arr, 1, 200, axis=1)

array([[  1, 200,   2,   3],
       [  4, 200,   5,   6],
       [  7, 200,   8,   9]])

In [223]:
# 요소마다 다른 값으로 행/열 추가하기
# 요소의 개수를 동일하게 작성 -> 촉을 기준으로 요소 개수 결정 -> axis로 축 설정
np.insert(arr,2,[10,20,30], axis=1)

array([[ 1,  2, 10,  3],
       [ 4,  5, 20,  6],
       [ 7,  8, 30,  9]])

3) 요소 삭제
- np.delete(arr, idx, axis=None)
    - 지정한 인덱스(idx)에 해당하는 요소를 삭제
    - axis 지정하지 않는 경우(기본값) : 1차원 배열로 변형되어 해당 인덱스에 해당하는 요소를 삭제
    - axis = 0 : 행 방향으로 n번째 행을 삭제
    - axis = 1 : 열 방향으로 n번째 열을 삭제
    - 원본 배열에 반영되지 않음

In [224]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [225]:
# a.reshape(9)
np.ravel(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [234]:
# axis를 지정 안 하는 경우 :1차원 배열로 변환 -> 지정한 index에 해당하는 요소를 삭제
# a배열에 대해 1번 인덱스 요소를 삭제
np.delete(a,1)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [228]:
# 원본 배열은 변경되지 않음
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [237]:
# a배열 세로축으로 0번째 삭제
np.delete(a,0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [238]:
# a배열 가로축으로 0번째 삭제
np.delete(a,0, axis=1)

array([[2, 3],
       [5, 6],
       [8, 9]])

4) 배열 결합
- np.concatenate((arr1, arr2, ...), axis=0)
    - axis = 0(기본값) : 행 방향으로 두 배열 결합 (단, 열의 개수가 동일)
    - axis = 1 : 열 방향으로 두 배열 결합 (단, 행의 개수가 동일)
    - 원본 배열들은 변경되지 않음

In [239]:
# 1이상 7미만의 범위에서 1씩 증가하는 숫자로 2 x 3 구조의 배열 a 생성
# 7이상 13미만의 범위에서 1씩 증가하는 숫자로 2 x 3 구조의 배열 b 생성
# 13이상 23미만의 범위에서 1씩 증가하는 숫자로 2 x 5 구조의 배열 c 생성(열개수 다름)
# 23이상 38미만의 범위에서 1씩 증가하는 숫자로 5 x 3 구조읩 배열 d 생성(행개수 다름)
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
c = np.arange(13, 23).reshape(2, 5)
d = np.arange(23, 38).reshape(5, 3)

In [241]:
print(a)
print()
print(b)
print()
print(c)
print()
print(d)
print()

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]

[[13 14 15 16 17]
 [18 19 20 21 22]]

[[23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]



In [243]:
# axis=0(기본값) : 행 방향으로 두 배열 결합
# np.append(a,b)
# [1,2,3,4,5,6,7,8,9,10,11,12]
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [244]:
# axis =1 열 방향으로 두 배열 결합
np.concatenate((a,b), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [246]:
# 행 방향으로 결합 : 열 개수가 동일해야함
np.conacatenate((a,c))

AttributeError: module 'numpy' has no attribute 'conacatenate'

In [248]:
np.concatenate((a,c), axis=1)

array([[ 1,  2,  3, 13, 14, 15, 16, 17],
       [ 4,  5,  6, 18, 19, 20, 21, 22]])

In [250]:
# 열 방향으로 결합 : 행 개수 동일
np.concatenate((a,d), axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 5

In [251]:
np.concatenate((a,d), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37]])

- np.split(arr, indices_or_sections, axis=0)
    - axis = 0(기본값) : 행 단위로 분리
    - axis = 1 : 열 단위로 분리
    - 원본 배열은 변경되지 않음

In [253]:
a = np.arange(1,37).reshape(6,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [260]:
# 균등하지 않게 행 기준으로 분리
# 리스트로 넘기면 위치를 지정합니다.
# 스칼라값을 넘기면 균등하게 갯수를 맞춰서 쪼개줍니다.
# 스칼라값으로 처리시 반드시 나눈 갯수가 정수로 떨어져야 합니다.
np.split(a,[1,2,3], axis=0)

[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

In [264]:
# 균등한 간격으로 열 기준으로 3개 분리
np.split(a,3, axis=1)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26],
        [31, 32]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28],
        [33, 34]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24],
        [29, 30],
        [35, 36]])]